Document and Test enum as union
plexinc/papr pull request #133
Opened 2021-11-23 21:03 UTC by jtassin

In my case, I want to avoid the usage of enum, replaced by union type.

I found out that `papr` works natively fine in this case :)

I just added a test on it and a piece of documentation.

Thx a lot for your lib btw :) 

```ts
tt: types.enum(
              [
                'FOO' as const,
                'BAR' as const,
              ],
              { required: true },
            ),
```

resolves as `'FOO' | 'BAR'`

2021-11-25 13:26 UTC, avaly requested changes

2021-11-25 13:26 UTC, avaly commented on src/__tests__/types.test.ts
> +      test('array of const', () => {
Please move this test after the `default` test case.

2021-11-25 13:26 UTC, avaly commented on docs/api/types.md
> +With `enum` you can either :
These docs files are generated from the JSDoc in the `src/` files. Please edit those original files first, then run `yarn docs` to generate these ones.

2021-11-25 13:28 UTC, avaly commented
Thanks for the contribution @jtassin! I just requested a few changes before we can merge this.

2021-11-29 07:55 UTC, jtassin commented
> Thanks for the contribution @jtassin! I just requested a few changes before we can merge this.

Thx @avaly : all done !

2021-11-29 08:24 UTC, avaly requested changes

2021-11-29 08:24 UTC, avaly commented on src/types.ts
> +   * - Creates an union type based on an array of `const`
```suggestion
   * - Create an enum type based on a TypeScript `enum` structure
   * - Create an union type based on an array of `const`
```

2021-11-29 08:24 UTC, avaly commented on src/types.ts
> +   *   requiredEnumAsUnion: types.enum(['foo' as const, 'bar' as const], { required: true }), // type is 'foo' | 'bar'
```suggestion
   *   optionalEnumAsConstArray: types.enum(['foo' as const, 'bar' as const], { required: true }), // type is 'foo' | 'bar' | undefined
   *   requiredEnumAsConstArray: types.enum(['foo' as const, 'bar' as const], { required: true }), // type is 'foo' | 'bar'
```

2021-11-29 10:55 UTC, jtassin commented
@avaly done again :)

2021-11-29 11:14 UTC, avaly commented
@jtassin Sorry to ask for changes again, but can you please rebase this PR on top of the latest `main` commit? I've pushed some changes related to the generated docs and prettier.

2021-11-29 13:57 UTC, jtassin commented
> @jtassin Sorry to ask for changes again, but can you please rebase this PR on top of the latest `main` commit? I've pushed some changes related to the generated docs and prettier.

^^ no problem

2021-11-30 17:05 UTC, jtassin commented
> @jtassin Sorry to ask for changes again, but can you please rebase this PR on top of the latest `main` commit? I've pushed some changes related to the generated docs and prettier.

done @avaly (sorry for the long delay)

2021-12-01 08:39 UTC, avaly approved these changes

2021-12-01 08:41 UTC, merged