fix: Allow explicit optional types on schemas
plexinc/papr pull request #207
Opened 2022-05-24 22:34 UTC by andersonjoseph

Hello!

This PR allows to declare explicit optional types for schemas.

Currently if we try to do something like this:
```ts
const value = schema({
  age: types.number({ required: false }),
});
// age: number
```
`age` will be still required even if  `required` is set as `false`. 

With this changes, schema returns the correct type when `{required: false}` is passed in the options object
```ts
const value = schema({
  age: types.number({ required: false }),
});
// age: number | undefined
```

Let me know how it looks and if something needs to be modified ✌

2022-05-25 07:01 UTC, avaly requested changes
Thanks for these changes. I left a few change requests that need addressing before we can merge this.

2022-05-25 08:19 UTC, avaly commented on docs/api/papr.md
> +## `Papr`
The docs should be fixed in `main`, please rebase your branch on top of the latest commit there.

2022-05-25 17:23 UTC, andersonjoseph commented
> Thanks for these changes. I left a few change requests that need addressing before we can merge this.

Done! I already made the changes and rebased to main, docs files are not being modified by `lintstaged` task.

2022-05-26 07:27 UTC, avaly approved these changes

2022-05-26 08:00 UTC, merged